- omero/developers/Web/CreateApp.txt
Updates the web CreateApp page to address a couple of small issues:
- previous instructions specified that the app directory itself was on the ```PYTHONPATH``` whereas it should be the parent directory that is on the ```PYTHONPATH```.
- import statements in the urls.py example don't work with 5.0 OMERO
To test, follow the CreateApp instructions until you have the "Welcome" message at a new app /index.html.
> Update CreateApp docs

- omero/developers/Web/PublicData.txt
This is the same as gh-1043 but rebased onto develop.
----
as indicated in http://lists.openmicroscopy.org.uk/pipermail/ome-users/2014-November/004914.html
To test. Setup public user with a following filter
```
$ bin/omero config set omero.web.public.url_filter '^/(?!webadmin|webclient/logout/|webclient/action/\w+|webclient/annotate_(file|tags|comment))'
```
1. Go to http://host/webclient. There will be no login page. You will be redirected directly to the public user data.
1. Click logout, you should be redirected to login page.
1. Log in as regular user. You should see own data.
1. Log out again. You should be redirect to public user data.
> adding logout to the filter (rebased onto develop)

- omero/sysadmins/index.txt
- omero/sysadmins/version-requirements.txt
Conversion of https://docs.google.com/spreadsheets/d/1TRJUhdMZ_pnHxg1TUk9Lf_oQcx2paZtwWMjTybQ7qZo/edit#gid=0 to sphinx markup
This isn't intended to mirror the installation prerequisites; it's primarily of interest to ourselves and sysadmins who need to know what's supported for the deployment timeframe of an OMERO installation.  From that point of view it's a much more detailed overview of each prerequisite, which could be cross-referenced from the install docs.  This is a detailed list of all of the released versions of our prerequisites, and their release and support timeframes.  It also details which versions are provided by each version of each distribution/operating system.  The intent is that this gives a detailed overview of what's supportable, and what's obsolete/unsupportable, …
> omero: Add detailed version requirements

- common/conf.py
- omero/developers/Web/CSRF.txt
- omero/developers/Web/CreateApp.txt
- omero/developers/Web/WritingTemplates.txt
- omero/sysadmins/unix/install-web.txt
- omero/sysadmins/windows/install-web.txt
- omero/sysadmins/windows/server-installation.txt
Existing link was making http://ci.openmicroscopy.org/view/Docs/job/OMERO-5.1-merge-docs/ yellow and when I hunted around, I found the topic was actually on a different page.
cc @aleksandra-tarkowska - if you are happy with this, I'll rebase to dev_5_0 once the build is green.
> Fixing broken anchor link

- common/conf.py
- omero/developers/Web/CSRF.txt
- omero/developers/Web/CreateApp.txt
- omero/developers/Web/WritingTemplates.txt
- omero/sysadmins/unix/install-web.txt
- omero/sysadmins/windows/install-web.txt
- omero/sysadmins/windows/server-installation.txt
This is the same as gh-1066 but rebased onto dev_5_0.
----
Existing link was making http://ci.openmicroscopy.org/view/Docs/job/OMERO-5.1-merge-docs/ yellow and when I hunted around, I found the topic was actually on a different page.
cc @aleksandra-tarkowska - if you are happy with this, I'll rebase to dev_5_0 once the build is green.
> Fixing Django doc links (rebased onto dev_5_0)

- omero/developers/Matlab.txt
This Pull Request adds the new annotations utility functions and a link to the `WriteData` example to the MATLAB developer page.
> Add double and timestamp MATLAB annotations functions to the table

- omero/developers/Matlab.txt
This is the same as gh-1059 but rebased onto dev_5_0.
----
This Pull Request adds the new annotations utility functions and a link to the `WriteData` example to the MATLAB developer page.
> Add double and timestamp MATLAB annotations functions to the table (rebased onto dev_5_0)

- omero/developers/Modules/Delete.txt
- omero/developers/Server/GraphsMigration.txt
- omero/developers/Server/ObjectGraphs.txt
- omero/developers/index.txt
- omero/developers/whatsnew.txt
- omero/sysadmins/whatsnew.txt
- omero/users/whatsnew.txt
The 5.0 graphs API is deprecated. This documentation tells users to migrate to the 5.1 API and gives some information about how.
As 5.2 and 5.3 are released, 5.0 graphs information can be removed from documentation: for graphs, 5.1 and 5.2 are transitional.
Mostly staged at http://www.openmicroscopy.org/site/support/omero5.1-staging/developers/whatsnew.html and http://www.openmicroscopy.org/site/support/omero5.1-staging/developers/Server/GraphsMigration.html.
--no-rebase
> clients to convert code using 5.0 graphs to 5.1 graphs

- omero/developers/Modules/Search.txt
The URL for Luke has moved.
Staged at https://www.openmicroscopy.org/site/support/omero5.1-staging/developers/Modules/Search.html.
--no-rebase for now
> fix URL for Lucene Index Toolbox

- omero/developers/Modules/Search.txt
The URL for Luke has moved.
Staged at https://www.openmicroscopy.org/site/support/omero5-staging/developers/Modules/Search.html.
--rebased-from #1077
> fix URL for Lucene Index Toolbox (rebased from develop)

- omero/sysadmins/server-upgrade.txt
- omero/sysadmins/unix/server-install-homebrew.txt
- omero/sysadmins/unix/server-installation.txt
- omero/sysadmins/unix/walkthrough/setup_postgres.sh
https://trello.com/c/Fv1HZVfs/779-virt-microscope-pg-9-for-testing reveals the need for a UTF8-encoded database for OMERO since 5.1 patch 12.
PostgreSQL 8.4 references can be updated once version prerequisites suggested via http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-January/004982.html are approved, so for now they are left alone.
--no-rebase
> adjust createdb commands to specify Unicode databases

- omero/sysadmins/in-place-import.txt
See: https://github.com/openmicroscopy/openmicroscopy/pull/3379
> Add cp/_rm section for 5.0.7

- omero/autogen_docs
First PR against the auto-generation script noticed while reviewing https://github.com/snoopycrimecop/ome-documentation/commit/b7a2a8555b0c08cbf5ce9c3b2ae7d59e8d4445d7#diff-fb1c64548e4bb9a6bc9dca21ffd8dae4R1. 
The argparse native help formatter splits paths on dashes. This has direct implications on the CI infrastructure where job names are separated by dashes and the path replacement logic is broken. This commit works around this limitation by running the `bin/omero ` command locally and not substituting the path to the server.
To test this PR, check the `develop/merge/autogen` branch of https://github.com/snoopycrimecop/openmicroscopy especially the `setdn.out` file changes.
> Workaround argparse help formatter dash limitation

- omero/sysadmins/unix/server-linux-walkthrough.txt
- omero/sysadmins/unix/walkthrough/install-centos6.sh
- omero/sysadmins/unix/walkthrough/setup_nginx_centos6_selinux.sh
Recent CentOS6 and external Nginx versions may result in SELinux blocking communication between Nginx and OMERO.web. https://www.openmicroscopy.org/community/viewtopic.php?f=5&t=7697&start=40#p15219
Should be rebased in time for the 5.0.7 release
Testing: You'll need a CentOS6 VM with SELinux enabled.
> SELinux walkthrough fixes

- omero/autogen_docs
This is the same as gh-1085 but rebased onto dev_5_0.
----
First PR against the auto-generation script noticed while reviewing https://github.com/snoopycrimecop/ome-documentation/commit/b7a2a8555b0c08cbf5ce9c3b2ae7d59e8d4445d7#diff-fb1c64548e4bb9a6bc9dca21ffd8dae4R1. 
The argparse native help formatter splits paths on dashes. This has direct implications on the CI infrastructure where job names are separated by dashes and the path replacement logic is broken. This commit works around this limitation by running the `bin/omero ` command locally and not substituting the path to the server.
To test this PR, check the `develop/merge/autogen` branch of https://github.com/snoopycrimecop/openmicroscopy especially the `setdn.out` file changes.
> Workaround argparse help formatter dash limitation (rebased onto dev_5_0)

- omero/sysadmins/unix/server-linux-walkthrough.txt
- omero/sysadmins/unix/walkthrough/install-centos6.sh
- omero/sysadmins/unix/walkthrough/setup_nginx_centos6_selinux.sh
- omero/sysadmins/unix/walkthrough/setup_postgres.sh
This is the same as gh-1086 but rebased onto dev_5_0, with the addition of the database UTF-8 specification,
----
Recent CentOS6 and external Nginx versions may result in SELinux blocking communication between Nginx and OMERO.web. https://www.openmicroscopy.org/community/viewtopic.php?f=5&t=7697&start=40#p15219
Should be rebased in time for the 5.0.7 release
Testing: You'll need a CentOS6 VM with SELinux enabled.
> SELinux walkthrough fixes (rebased onto dev_5_0)

- omero/sysadmins/unix/server-install-homebrew.txt
This is the same as gh-1091 but rebased onto dev_5_0.
----
With the migration of the script to the omero-install repository, the
link on the documentation page needs to be updated
> Fix link to Homebrew installation script (rebased onto dev_5_0)

- omero/sysadmins/unix/server-install-homebrew.txt
With the migration of the script to the omero-install repository, the
link on the documentation page needs to be updated
> Fix link to Homebrew installation script

- README.rst
- omero/autogen_docs
In preparation of the deprecation of the `OMERO.clients` bundle on 5.1.0, this PR removes their need for the auto-generated documentation. Instead, it uses the `--java-help` option of the CLI import plugin which dumps the content of `importer-cli`.
To test this PR, check the outcome of the the auto-generated importer help is the same with and without this PR (e.g. by comparing the `develop/latest/autogen` and `develop/merge/autogen` branches of https://github.com/snoopycrimecop/ome-documentation).
--no-rebase
> Autogen clients deprecation

- omero/developers/testing.txt
Following the structural changes in https://github.com/openmicroscopy/openmicroscopy/pull/3318 and https://github.com/openmicroscopy/openmicroscopy/pull/3405, this PR review the OMERO developer page about running and writing tests by:
- moving all aspects about running tests to the first section incl. Java/Python specific sections
- describe the library structure for Omero.Py and OMERO.py
- providing some basic description of the ``ITest` and ``IWebTest`` most useful features/methods
/cc @will-moore @ximenesuk 
--no-rebase
> Document the Python integration library

- omero/sysadmins/server-upgrade.txt
Staged at https://www.openmicroscopy.org/site/support/omero5.1-staging/sysadmins/server-upgrade.html. Removes some to-5.0-specific text, refers those users to the 5.0 upgrade instructions, and adds some hints about how to ensure a Unicode-encoded OMERO DB.
--no-rebase
> in upgrade tell sysadmins to first ensure Unicode DB

- omero/sysadmins/search.txt
Following http://lists.openmicroscopy.org.uk/pipermail/ome-users/2015-February/005038.html, the re-indexing times indicated in our docs is out-of-date are largely overestimated.
This PR updates the re-indexing estimated times using:
- data from a background re-indexing of a production database - courtesy of @ehrenfeu 
- data from an off-line re-indexing of a similarly sized production database
Minor nitpicks/corrections are also added to the off-line re-indexing section.
> Update re-indexing table

- omero/conf.py
This message is going once we release anyway, but thought I'd update it for the m4 docs just to avoid any confusion.
> Updating link to 5.0.x docs

- omero/sysadmins/unix/server-installation.txt
- omero/sysadmins/windows/server-installation.txt
See https://github.com/PyTables/PyTables/issues/420#issuecomment-75062287 - www.pytables.org is currently shutdown. This should make the build green again.
> Updating pytables external link

- omero/developers/Modules/searchfieldnames.tsv
Brief explanation of the name:value and the has_key:name
entries which are now possible in 5.1.
> Map index documentation

- omero/developers/Model/EveryObject.txt
Now includes `Image.series`. Staged at https://www.openmicroscopy.org/site/support/omero5.1-staging/developers/Model/EveryObject.html.
--no-rebase and, one hopes, now finalized for 5.1
> autogenerated: update reference for every OMERO model object

- common/conf.py
- formats/developers/structured-annotations.txt
This makes all 5.1/2015-01 Model docs link to each other by specific branch, mostly so the new Model docs link to the m4 docs before we automatically redirect all the 5 links to 5.1
> Making doc links 5.1 specific

- omero/sysadmins/server-upgrade.txt
By expanding some of the server upgrade text with phrases close to what the actual upgrade script error messages are, people googling those messages may be made more likely to find this page. Staged at http://www.openmicroscopy.org/site/support/omero5.1-staging/sysadmins/server-upgrade.html.
--no-rebase
> SQL errors on server upgrade

- omero/developers/Server/GraphsMigration.txt
Companion PR to https://github.com/openmicroscopy/openmicroscopy/pull/3515. Staged at http://www.openmicroscopy.org/site/support/omero5.1-staging/developers/Server/GraphsMigration.html.
--no-rebase
> add Java examples to graphs migration page

- omero/developers/Server/Properties.txt
People wanting to know more about server configuration are probably better directed to the general sysadmin page than the overview. Staged at http://www.openmicroscopy.org/site/support/omero5.1-staging/developers/Server/Properties.html.
--no-rebase
> adjust server config link

- omero/developers/Modules/Delete.txt
Staged at http://www.openmicroscopy.org/site/support/omero5.1-staging/developers/Modules/Delete.html#binary-data to satisfy https://trello.com/c/zi1NKnrs/287-find-existing-fs-directories.
--no-rebase
> add note about cleanse deleting empty directories

- omero/sysadmins/server-ldap.txt
Some basic clarification which will be useful for non-LDAP gurus trying to use an LDAP service to authenticate and get group information.
> Add brief explanation of the difference between DN and other LDAP attributes

- .travis.yml
Similar fix as in https://github.com/openmicroscopy/bioformats/pull/1657. Travis is currently failing because our documentation does not build cleanly with Sphinx 1.3.0
> Use Sphinx 1.2.3 for Travis build

- omero/sysadmins/server-upgrade.txt
When upgrading our OMERO server from 5.0.0 to 5.0.8, I had an issue
where OMERO.web did not display things properly afterward. The problem
was that although we use a "future-proof" symlink, pointing the 'omero'
folder to whatever the current version is (e.g.,
OMERO.server-5.0.8-ice34-b60), the "bin/omero web config" configuration
stanza generator used the hardcoded version-specific folder name, which
I failed to adjust when I did the 5.0.0 install. So in short, my Apache
configuration was outdated.
Just another pitfall which might be worth mentioning in the upgrade
documentation, since there is already a handy checklist.
> Add a note to double check OMERO.web config

- omero/developers/Web.txt
- omero/developers/Web/CreateApp.txt
- omero/developers/Web/WritingViews.txt
This PR update some sample code to the Django standards
To test it, for example create simple form and use ```render``` on HTTP POST. You should not get 403 as ```RequestContext``` is forced and ```{% csrf_token %}``` will be used.
cc @will-moore 
--no-rebase
> updating developers/web doc

- omero/sysadmins/unix/server-installation.txt
- omero/users/cli/installation.txt
- Add link to version requirements
- Mark both OMERO.py and OMERO.server as CLI containers (with caveats)
- Fix CLI shell code block
/cc @ximenesuk
--no-rebase
> CLI installation

- omero/users/cli/overview.txt
- omero/users/cli/sessions.txt
See https://trello.com/c/Lo6MKBRY/298-5-1-cli
This page improves the `omero login` documentation and simplifies the overview section for the CLI.
As requested, the `-k KEY` argument should be better exposed with this change /cc @joshmoore.
--no-rebase
> Review CLI overview/sessions pages

- formats/ome-tiff/tools.txt
See https://ci.openmicroscopy.org/view/Docs/job/FORMATS-merge-docs/631/warnings3Result/ - the BF cpp docs moving broke the link in the Model Docs. Given the 5.1 docs are now live since the m5 release, I thought it was fine to link to them now.
cc @rleigh-dundee
> Update BF cpp doc link in Model Docs

- omero/developers/Web/PublicData.txt
This improves the docs for using webclient UI for public data. See discussion at https://www.openmicroscopy.org/community/viewtopic.php?f=5&t=7761&start=10#p15517
Here I've attempted to provide a url filter that blocks all the urls you might want to disable from a public facing site, while still allowing webclient UI.
Also I've removed the advice "You probably do not want the whole webclient UI to be publicly visible" since many people do want to do this, and we now support it better.
To test, please set the described url filter and see if webclient becomes "browse only" (can't create data or run scripts etc). Also see https://gist.github.com/will-moore/8315580 (do we want to bring this into our docs or link to it from anywhere)?
> Improve public url_filter docs

- omero/autogen_docs
- omero/users/cli/overview.txt
- omero/users/cli/tag.txt
Minor fixes for the CLI documentation pages in preparation of 5.1.0
- fixes a command typo spotted by @manics 
- lists options for `bin/omero help`
--no-rebase
> CLI: minor fixes

- .gitignore
Related to the failure of https://ci.openmicroscopy.org/job/OMERO-5.1-release/36/. /cc @joshmoore 
Dangling `pyc` files (`omero/conf_autogen.pyc`) broke the `git describe` logic. This commit is making sure these files are ignored.
--no-rebase
> Ignore pyc files

- omero/sysadmins/unix/server-install-homebrew.txt
- Delete information for MacOS 10.7 and earlier, since it's no longer supported by us or homebrew
- Use new Xcode and Java install instructions
- Use current Homebrew dependency versions
- Recommend use of Homebrew Python over system Python
- Use current Homebrew wiki links
- Use Python 2.7 only (2.6 no longer provided by MacOS X or homebrew)
- Set environment at appropriate places in the script so it's correct in the places which depend upon it (`PATH` and `PYTHONPATH`)
- Drop `/usr/local/lib/node_modules` from the user `PATH`; it's not part of any of our other installation instructions and appears to be redundant (used in the past?)
- Reword PostgreSQL installation steps
- Drop old Homebrew problems which are no longer applicable
- Don't invoke an executable shell script with a shebang …
> homebrew: Update for current homebrew and supported platforms

- omero/downloads/inplace/advanced-help.txt
- omero/sysadmins/unix/apache-fcgi-omero.conf
- omero/sysadmins/unix/apache-omero.conf
- omero/users/history.txt
Repository: openmicroscopy/ome-documentation
Already up-to-date.
Generated by build [OMERO-5.1-latest-docs-autogen#534](https://ci.openmicroscopy.org/job/OMERO-5.1-latest-docs-autogen/534/).
----
--no-rebase
> Update auto-generated documentation

- omero/sysadmins/server-upgrade.txt
This notice should warn sysadmins of the memo file invalidation/re-generation post upgrade as noticed by @dominikl during testing. 
--no-rebase
> Add paragraph about memo file invalidation post-upgrade

- omero/sysadmins/whatsnew.txt
It's not clear from the rest of the docs that 9.2 is the minimum.
> Add postgres 9.2 requirement to sysadmin what's new

- omero/sysadmins/server-upgrade.txt
Following a 5.1 upgrade the Blitz log may have loads of ERRORs message about old memoization files. One way around this is to delete the BioFormatsCache directory.
--no-rebase
> Add note about optionally deleting BioFormatsCache files

- omero/users/cli/sessions.txt
This should replace the deprecated OMERO_SESSION_DIR envvar
Documents code changes in https://github.com/openmicroscopy/openmicroscopy/pull/3742
> Document new OMERO_SESSIONDIR environment variable

- .travis.yml
saucy has been removed from the mirrors and was no longer supported.
Note the reordering of the graphviz install to use precise;
for some reason the trusty version fails to install due to
some (unrevealed) dependency problem installing libgvc6.
--------
Testing: travis should be green.
> travis: Switch from saucy to trusty

- .travis.yml
- README.rst
- contributing/ci-bio-formats.txt
- contributing/ci-consortium.txt
- contributing/ci-docs.txt
- contributing/ci-introduction.txt
- contributing/ci-omero.txt
- contributing/ci-release.txt
This PR:
- removes the usage of `graphviz` in the Contributing documentation
- removes all CI jobs related to the 4.4.x development line
> Contributing cleanup

- omero/sysadmins/limitations.txt
- omero/sysadmins/troubleshooting.txt
- omero/sysadmins/unix/server-installation.txt
- omero/sysadmins/windows/server-installation.txt
Re-arranged troubleshooting page and added mention of the ulimit issue to the server installation pages (I've stuck it under advanced configuration as it seemed the most logical place but I'm open to suggestions if others can think of a better place for it). Also added cross-reference to the Windows database encoding issue on the troubleshooting page and fixed the web subheading pointed out by Roger on a previous PR.
> Adding better ulimit info & cross-references

- formats/ome-tiff/code.txt
- formats/ome-tiff/specification.txt
- Correct some descriptions to take BigTIFF into account (non-breaking)
- Add `.ome.tf2`, `.ome.tf8` and `.ome.btf` file extensions (non-breaking for writers, but may cause problems with older readers)
--------
This is a proposed update to the OME-TIFF specification to allow the Bio-Formats readers and writers to be updated to use these extensions.  This will allow Bio-Formats' OMETiffWriter to enable use of BigTIFF when these extensions are used, and OMETiffReader to identify and read files using these extensions.
See also: https://github.com/openmicroscopy/bioformats/pull/1744
/cc @ehrenfeu
> OME-TIFF specification: Allow use of BigTIFF file extensions

- omero/developers/Modules/TempFileManager.txt
- omero/sysadmins/system-requirements.txt
- omero/sysadmins/troubleshooting.txt
- omero/sysadmins/unix/server-installation.txt
- omero/sysadmins/windows/server-installation.txt
- omero/users/cli/overview.txt
- omero/users/cli/sessions.txt
This PR documents the feature additions in https://github.com/openmicroscopy/openmicroscopy/pull/3789
- use `OMERO_TMPDIR` rather than `OMERO_TEMPDIR` across the documentation
- mention `OMERO_USERDIR` (for alternate sessions storage directory) under `omero/cli/sessions`
- mention and describe `bin/omero help env` in the overview page
- add a table listing all the client directories and their environment variables
> CLI envvars 5.1.2

- omero/sysadmins/unix/server-installation.txt
- https://trello.com/c/xDMnFnPd/498-fix-omero-web-var-permissions
- https://github.com/openmicroscopy/openmicroscopy/pull/3818
`etc` and `var` contain sensitive data, and on shared machines should be protected.
> Recommend chmod 700 OMERO.server directory

- omero/sysadmins/unix/server-installation.txt
The Python-based Homebrew package names do not have a `python/` prefix (anymore?). The `postgresql` package installs the latest, currently 9.4.
> server-installation: fix Homebrew package names

- omero/sysadmins/troubleshooting.txt
Following recent community reports about `Directory exists but is not registered: CheckedPath(username_id)` import errors, this PR adds this import error to the troubleshooting section of the documentation with minimal suggestions and links to the community threads.
/cc @mtbc @joshmoore
> Troubleshooting CheckedPath error

- omero/developers/cli/extending.txt
- omero/developers/cli/index.txt
- omero/developers/cli/obj.txt
Following the CLI restructuring carried out in https://github.com/openmicroscopy/ome-documentation/pull/1151, this PR now splits the CLI developer documentation into separate pages.
> Split CLI developer documentation

- omero/sysadmins/dropbox.txt
This PR advises sysadmins on how best to handle permissions changes of DropBox directories. The restart sequence in this PR needs testing. With DropBox running (confirm via diagnostics) disable and then stop both servers. Confirm via diagnostics. Then restart both servers in the order given. Both should be active according to diagnostics. Confirm that the MonitorServer log ends with something like,
```
...
2015-05-26 18:51:20,200 INFO  [                fsserver.fsMonitorServer] (Dummy-3   ) Monitor id = d07d34dc-03cf-11e5-8d75-3c075416fb46 created. Proxy: DropBox.default -t -e 1.1 @ DropBox.omerofs.DropBox
2015-05-26 18:51:20,201 INFO  [                fsserver.fsMonitorServer] (Dummy-5   ) Monitor id = d07d34dc-03cf-11e5-8d75-3c075416fb46 started
```
**Note**: If the log ends with just, …
> Add permissions advice to DropBox page

- omero/developers/cli/index.txt
- omero/index.txt
- omero/sysadmins/cli/index.txt
- omero/sysadmins/version-requirements.txt
- omero/users/cli/index.txt
- omero/users/index.txt
As I commented on Colin's last CLI user docs PR, these docs are quite buried so this tries to signpost them better now that they are more extensive. I've also tried to make the page titles clearer and have them distinguish between the doc sections because as @mtbc has pointed out before, if you use the search box on the website to find CLI docs, the results only give the page title, meaning you have to follow the link or note the full URL to see whether you're in the users, sysadmins or developer section docs.
> Signposting CLI docs better & minor tidy

- omero/developers/Model/Units.txt
As a part of https://trello.com/c/vdyTStEq/330-unit-documentation,
this copies work from:
* https://github.com/openmicroscopy/openmicroscopy/pull/3831 and
* https://github.com/joshmoore/ome-units/blob/master/units/Fields.txt
into `Model/Units.txt`. @chris-allan rightly pointed out that this was
sorely lacking and should be clearly linked for anyone who needs to
upgrade their code from 5.0.
> Unit queries

- formats/developers/ome-units.txt
- omero/developers/Model/EveryObject.txt
- omero/developers/Model/Units.txt
See https://trello.com/c/vdyTStEq/330-unit-documentation - adds to #1222 by cross-referencing Data Model and OMERO developer units docs pages. Also adds API doc links to Laser wavelength on the Model Objects doc page.
> Adding units docs cross-references

- omero/developers/Model/EveryObject.txt
- omero/developers/Model/Units.txt
- omero/developers/whatsnew.txt
- omero/sysadmins/index.txt
- omero/sysadmins/whatsnew.txt
- omero/users/whatsnew.txt
Promoting Read-Write groups and updated Units and Publishing docs in the what's new pages.
@joshmoore if you want to submit a PR against this to add a **brief** summary of the breaking changes re: units to the developer page, go ahead. Otherwise, it can be added when you and Mark get the queries info documented.
> Updating what's new pages for point release stuff

- omero/sysadmins/version-requirements.txt
https://developer.apple.com/graphicsimaging/opengl/capabilities/index.html link in the doc was upsetting the Jenkins build because it is being redirected to https://developer.apple.com/opengl/capabilities/index.html
> Fixing redirecting OpenGL Apple dev link

- omero/sysadmins/UpgradeCheck.txt
Removing an internal section reported by Kenny (see https://trello.com/c/PAXHlAne/344-ome-registry-version-update-in-public-docs) and also stopping the link to the upgrade URL which redirects to version 4 docs being live after the discussion in devteam the other day (I realise the link needs updating in the qa repo and this is on the list somewhere, but there is no really no need to encourage people reading the docs to click on the link by having it live in the docs page, especially as once it is fixed, it will redirect you to the same page you are already on!).
> Updating Upgrade Check page

- contributing/ci-bio-formats.txt
- contributing/ci-omero.txt
- contributing/ci-release.txt
This commit should update the CI pages of the contributing documentation to
reflect the changes required post-merging of the OMERO/Bio-Formats build
decoupling PR.
> Update CI job names and pipelines post Bio-Formats decoupling

- README.rst
- common/conf.py
- omero/developers/build-system.txt
- omero/sysadmins/troubleshooting.txt
- omero/sysadmins/version-requirements.txt
Should fix https://ci.openmicroscopy.org/job/OMERO-5.1-merge-docs/ which fails on search.maven.org. Also fixes the ZeroC and Python default hyperlinks/extlinks to prevent unnecessary redirects in the link checker.
> Hyperlink fixes

- omero/sysadmins/unix/server-linux-walkthrough.txt
- omero/sysadmins/unix/walkthrough/settings.env
Omits the header comment introduced by https://github.com/ome/omero-install/pull/35 from the literal include on http://www.openmicroscopy.org/site/support/omero5.1-staging/sysadmins/unix/server-linux-walkthrough.html.
> do not show settings.env header comment on walkthrough page

- omero/sysadmins/mail.txt
Replaces #1241
Should get rid of the purple highlighting in plone and also clarifies the mail.from property
> Fixing formatting on omero.mail page

- omero/sysadmins/limitations.txt
- omero/sysadmins/server-ldap.txt
- omero/sysadmins/whatsnew.txt
See https://trello.com/c/o9B6tmfG/323-5-1-2-updates-to-known-limitations-page - LDAP improvements hadn't been fed through to the limitations doc for 5.1.2
> Updating LDAP docs

- README.rst
- common/conf.py
- contributing/conf.py
- contributing/team-communication.txt
- formats/developers/index.txt
- formats/ome-xml/index.txt
With the recent switch to trac.openmicroscopy.org as the default domain, this
should avoid unnecessary redirects while checking URLs.
> Update all Trac links to use HTTPS URL ending with .org

- common/conf.py
See https://trello.com/c/3yYuGGxL/155-dev-5-1-branch-creation-tasks
Once built, the 'Show on Github' and 'Edit on Github' links at the bottom of the sidebar on all the OMERO 5.1-staging pages should point at the dev_5_1 branch rather than develop
> Updating branch of 'source/edit on github' links

- omero/developers/Server/GraphsMigration.txt
- omero/developers/whatsnew.txt
See http://www.openmicroscopy.org/site/support/omero5.1/developers/whatsnew.html and http://www.openmicroscopy.org/site/support/omero5.1/developers/Server/GraphsMigration.html for mentions of how Chmod has been replaced.
> add note of Chmod2 to graphs documentation

- omero/developers/Model/EveryObject.txt
Automatically generated from openmicroscopy/openmicroscopy#4010. Staged at http://www.openmicroscopy.org/site/support/omero5.1-staging/developers/Model/EveryObject.html. There should now be links from dimensioned quantities to reasonable units Javadoc.
Also shortens anchor names.
--rebased-from #1251
> update EveryObject OMERO model glossary (rebased from develop)

- omero/developers/Web/ViewPort.txt
Ola's PR https://github.com/openmicroscopy/openmicroscopy/pull/4023 removed the web examples as they are now in webtest, this updates the link in the web developer docs to point at the new location.
> Updating web example links to webtest

- omero/sysadmins/grid.txt
This is the same as gh-1267 but rebased onto dev_5_1.
----
See https://trello.com/c/ixjHtzgp/364-explicitly-don-t-support-windows-grid-clusters - notes to make clear that multi-node configurations are not supported for Windows.
Will be staged on https://www.openmicroscopy.org/site/support/omero5.1-staging/sysadmins/grid.html once built.
Will be rebased to dev_5_1 for the 5.1.4 release once reviewed.
> Multi-nodes not supported on Windows (rebased onto dev_5_1)

- omero/users/cli/delete.txt
- omero/users/cli/tag.txt
This PR makes a couple of chnages to the CLI tag documenation. One is related to a commit on https://github.com/openmicroscopy/openmicroscopy/pull/4061 allowing tags to be created without a description.
The second relates to deleting tags and is in response to https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=7884&p=16139#p16137 
A question regarding this second commit is whether the examples should be added to the `delete` page and a simple link be provided or if it is okay to have this explanation of one aspect of a command on anthor command page.
--rebased-to #1270
> Modify CLI tag page

- omero/developers/Matlab.txt
See https://trello.com/c/gSKqCAe2/49-omero-matlab-group-support
This PR:
- reviews the `writexxAnnotation` functions giving concrete examples for each existing annotation type
- adds example of annotation writing command in a different group
- documents the project/dataset/screen/plate creation functions with and without group support
> Matlab: add documentation for write functions group support

- .travis.yml
This is the same as gh-1280 but rebased onto dev_5_1.
----
This PR  migrates the Travis build to using Docker containers in order to speed up build times as well as the queuing for the organization.
Like https://github.com/openmicroscopy/bioformats/pull/1968, one caveat of this PR is that it drops the `pdf` target of the top-level build command. This target is however tested by the various Jenkins doc jobs.
> Migrate to Travis Docker container (rebased onto dev_5_1)

- omero/developers/scripts/matlab-scripts.txt
This should fix the broken links reported from the linkcheck target of the OMERO documentation.
> Fix installation link for MlabWrap

- README.rst
- omero/conf.py
Quick tidy-up for 5.1.4 release - not very new any more to need docs banner and Model & contributing docs not maintained on this branch.
> Remove 'new version' docs banner & update README
