openmicroscopy/ome-documentation

omero/developers/Server/ObjectGraphs.txt
documents the change in https://github.com/openmicroscopy/openmicroscopy/pull/3321
--no-rebase
=> update according to adjustments in logback.xml

omero/developers/testing.txt
This PR supports a couple of currently open PRs: https://github.com/openmicroscopy/openmicroscopy/pull/3310 and https://github.com/openmicroscopy/openmicroscopy/pull/3319  It should only be considered for merging once both of those two are merged.
--no-rebase
=> Updates to testing page

omero/developers/testing.txt
Add instructions corresponding to the changes in https://github.com/openmicroscopy/openmicroscopy/pull/3296
--no-rebase
=> Mention Python library path when using py.test directly

omero/sysadmins/config.txt
Repository: openmicroscopy/ome-documentation
Already up-to-date.
Generated by build [OMERO-5.1-latest-docs-autogen#326](http://ci.openmicroscopy.org/job/OMERO-5.1-latest-docs-autogen/326/).
----
--no-rebase
=> Update auto-generated properties

omero/developers/Tables.txt, omero/developers/whatsnew.txt
Documentation for openmicroscopy/openmicroscopy#3249 (includes breaking changes)
--no-rebase
=> Update OMERO.tables 5.1 docs

omero/developers/Model.txt, omero/developers/Model/EveryObject.txt, omero/developers/index.txt
This is a newly created document that, as a developer, I've often wished I had. Staged at https://www.openmicroscopy.org/site/support/omero5-staging/developers/Model/EveryObject.html and fixes http://trac.openmicroscopy.org.uk/ome/ticket/12140.
--rebased-to #1081
=> OMERO model object reference

omero/sysadmins/dropbox.txt
This PR supports the changes in https://github.com/openmicroscopy/openmicroscopy/pull/3361
I'd welcome comments on wording, location, and mark-up!
=> Document DropBox on untested Windows.

omero/developers/Model.txt, omero/developers/Model/EveryObject.txt, omero/developers/index.txt
This is a newly created document that, as a developer, I've often wished I had. Staged at https://www.openmicroscopy.org/site/support/omero5.1-staging/developers/Model/EveryObject.html and fixes http://trac.openmicroscopy.org.uk/ome/ticket/12140.
--rebased-from #1076
=> OMERO model object reference (rebased from dev_5_0)

omero/sysadmins/dropbox.txt
his PR supports the changes in openmicroscopy/openmicroscopy#3360 This is a partial rebase as the underlying develop work is a little different
--rebased-from #1078
=> Document DropBox on untested Windows (develop)

omero/sysadmins/in-place-import.txt
This is the same as gh-1079 but rebased onto develop.
----
See: https://github.com/openmicroscopy/openmicroscopy/pull/3379
=> Add cp/_rm section for 5.0.7 (rebased onto develop)

contributing/ci-docs.txt
Follow-up of https://github.com/openmicroscopy/ome-documentation/pull/1083 and https://github.com/openmicroscopy/ome-documentation/pull/1084 on the contributing documentation
--no-rebase
=> Mention autogen_docs script in OMERO autogen jobs documentation

omero/sysadmins/unix/server-linux-walkthrough.txt
Additional commit from dev_5_0 gh-1090 copied back to develop.
=> SELinux walkthrough fixes (rebased onto dev_5_0) (rebased onto develop)

formats/developers/6d-7d-and-8d-storage.txt, formats/developers/index.txt, formats/developers/model-overview.txt, formats/developers/sample-files.txt, formats/developers/using-ome-xml.txt, formats/index.txt, formats/ome-tiff/data.txt, formats/ome-tiff/specification.txt, formats/schemas/index.txt, formats/schemas/january-2015.txt, formats/specifications/compliant-hcs.txt, formats/specifications/index.txt, formats/specifications/minimum.txt
Documentation updates for the Data Model docs for the new Schema - staged at https://www.openmicroscopy.org/site/support/ome-model-staging/
=> Initial 2015-01 additions

contributing/ci-docs.txt
Staged at https://www.openmicroscopy.org/site/support/contributing-staging/ci-docs.html#term-bioformats-5-1-merge-docs-autogen.
--no-rebase for contributing docs
=> BIOFORMATS-5.1-merge-docs-autogen builds Bio-Formats documentation

omero/sysadmins/troubleshooting.txt
Fixes https://trac.openmicroscopy.org.uk/ome/ticket/12527
=> Mention new templates.xml memory settings in troubleshooting section

formats/specifications/compliant-hcs.txt, formats/specifications/index.txt, formats/specifications/minimum.txt
I also validated the sample code looking for errors, none found.
=> Fix wording around specification samples

omero/sysadmins/version-requirements.txt
Remove "proposal" from the changes.
=> omero: Finalise minimum version requirements

formats/ome-tiff/index.txt
=> Tidying on Model docs

omero/index.txt, omero/users/index.txt, omero/users/whatsnew.txt
See https://trello.com/c/bm6wvqIt/147-data-model-docs-updates
=> Updating schema link and users what's new for 5.1

omero/developers/Model/StructuredAnnotations.txt
Remove WellSample from the list.
----
--no-rebase
=> WellSample is no longer annotatable

omero/developers/testing.txt
This PR documents the latest integration tests improvements added in https://github.com/openmicroscopy/openmicroscopy/pull/3618
--no-rebase
=> Extend testing page to cover new ITest features

omero/sysadmins/unix/install-web.txt, omero/sysadmins/version-requirements.txt, omero/sysadmins/windows/install-web.txt
First set of web docs changes for https://trello.com/c/ktgSRtvD/283-5-1-web-configuration
--no-rebase
=> Web config changes

omero/developers/Web/PublicData.txt
this helps to login using session key
=> adding password-less authentication example

omero/sysadmins/advanced-install.txt, omero/sysadmins/installing-scripts.txt, omero/sysadmins/mail.txt, omero/sysadmins/server-tables.txt
This documents the work from:
* https://github.com/openmicroscopy/openmicroscopy/pull/3542
* https://github.com/openmicroscopy/openmicroscopy/pull/3434
and aims to document all the various components (user, dev, sysadmin) for the OMERO.mail subsystem.
=> Email documentation

omero/users/whatsnew.txt
See various cards in the 5.1 doc tasks column
=> Updating what's new pages

omero/developers/Web/WritingViews.txt
Replacement for #1161 with fixes ready for m5
=> Render_response

omero/downloads/cli/help.out, omero/downloads/inplace/advanced-help.txt, omero/downloads/ldap/setdn.out, omero/sysadmins/config.txt, omero/sysadmins/unix/apache-fcgi-omero.conf, omero/sysadmins/unix/apache-omero.conf, omero/sysadmins/unix/nginx-omero.conf, omero/users/history.txt
Repository: openmicroscopy/ome-documentation
Already up-to-date.
Generated by build [OMERO-5.1-latest-docs-autogen#484](https://ci.openmicroscopy.org/job/OMERO-5.1-latest-docs-autogen/484/).
----
--no-rebase
=> Update auto-generated documentation

omero/conf.py, omero/index.txt, omero/sysadmins/limitations.txt
Adding a new limitation and some fixing and tidying ready for the release.
=> 5.1 docs updates

omero/developers/Clients/ImportLibrary.txt, omero/developers/ImportFS.txt, omero/developers/Server/FS.txt, omero/developers/index.txt, omero/sysadmins/import-scenarios.txt, omero/sysadmins/in-place-import.txt
Fixes https://trac.openmicroscopy.org.uk/ome/ticket/11803 and staged at http://www.openmicroscopy.org/site/support/omero5.1-staging/developers/ImportFS.html.
@joshmoore and @ximenesuk: Please read the commits carefully (except for the paragraph rewraps!) and the staging page to see what I got wrong or missed. I'll be happy to make further changes that you suggest.
--no-rebase
=> fix #11803: adjust text about OMERO.fs import

omero/developers/Web/WritingViews.txt, omero/sysadmins/mail.txt
Doc for https://github.com/openmicroscopy/openmicroscopy/pull/3656
cc: @joshmoore @sbesson
=> web notification for admin

omero/sysadmins/system-requirements.txt
As mentioned on #1177 the system requirements page was still showing old Java etc recommendations. This PR restructures the page to flow better into the new version requirements and less new example set-ups pages and avoiding having yet another place to forget to update things
cc @rleigh-dundee 
Note - I still need to check and update the storage requirements for the client bundle, will add that shortly
=> Updating system requirements

omero/conf.py, omero/sysadmins/server-upgrade.txt
See https://www.openmicroscopy.org/community/viewtopic.php?f=5&t=7778
Check:
- there is no more 4.4 mention on the ugprade page
- the note about using `SQL Shell` describes the workflow corresponding to the forum thread
--no-rebase
=> Upgrade minor fix

omero/developers/Java.txt
Fixes all the bugs/deprecated methods part of the documentation.
=> Doc Fix: Omero Java bindings

contributing/ci-omero.txt
Add the Windows 2012 OMERO deployment jobs to contributing.
=> Add OMERO-5.1-{latest,merge}-deploy-win2012

omero/sysadmins/in-place-import.txt
See https://trello.com/c/O1hKo873/321-5-1-2-inplace and https://www.openmicroscopy.org/community/viewtopic.php?f=5&t=7798
=> Adding umask for system user in inplace import

formats/developers/model-overview.txt, formats/developers/structured-annotations.txt
=> fix structured annotation typo

omero/sysadmins/limitations.txt, omero/sysadmins/windows/server-installation.txt
See https://trello.com/c/CVUflk8g/490-encoding-for-db-init-upgrade-script
Documents how to update upgrade script for DB until we get it fixed properly
=> known limitations warning for DB client encoding

formats/developers/id-and-lsid.txt, omero/developers/Model/Units.txt
Trivial fixes, but if I do them as I see them, they'll mostly end up done!
=> fix minor typos

omero/sysadmins/troubleshooting.txt
This PR:
- remove out of date OMERO.web troubleshooting sections
- adds a section about the `Permission denied` error with the default Apache stanza
/cc @manics @aleksandra-tarkowska
=> Web troubleshooting

omero/sysadmins/server-permissions.txt
Adding Read-write groups requires update of permissions docs (see https://github.com/openmicroscopy/openmicroscopy/pull/3783). Have also taken the opportunity to tidy up and improve styling.
Another commit to come to add read-write to tables.
=> Updating permissions page

omero/users/cli/chgrp.txt, omero/users/cli/delete.txt, omero/users/cli/index.txt
This PR adds page for the CLI `chgrp` and `delete` commands. The documentation should match and suitably illustrate the work in the PRs  https://github.com/openmicroscopy/openmicroscopy/pull/3725, https://github.com/openmicroscopy/openmicroscopy/pull/3824 and https://github.com/openmicroscopy/openmicroscopy/pull/3821
--no-rebase
=> Document CLI delete & chgrp

omero/sysadmins/server-backup-and-restore.txt
Broken link reported by Kenny.
=> Fixing download link on back-up&restore page

omero/conf.py, omero/developers/build-system.txt
As part of the decoupling effort, this PR is a first attempt at re-organizing, extending and improving the documentation of the build system. The PR describes the current state of the build system. Another PR  will be opened later highlighting its changes specific to the Bio-Formats decoupling effort.
This work is still in progress but feedback on the current state is welcome.
/cc @bramalingam @hflynn @jburel
=> OMERO build documentation review

omero/developers/build-system.txt, omero/developers/installation.txt, omero/developers/whatsnew.txt
See https://trello.com/c/phTsSDsj/25-documentation-changes-scoping
These changes should modify the developers documentation to cover the changes brought into the mainline with https://github.com/openmicroscopy/openmicroscopy/pull/3931
=> Bio-Formats decoupling: developer docs

omero/developers/whatsnew.txt
See https://trello.com/c/o67lmdg6/34-removal-of-locked - adds breaking change of '-locked' removal to developers what's new page
=> Removal of locked

omero/developers/Modules/Api/AdminInterface.txt, omero/developers/Server/CollectionCounts.txt, omero/developers/Server/ExtendingOmero.txt, omero/developers/Server/Sessions.txt, omero/developers/Web/WritingViews.txt
Various bits and bobs that came up as I was reviewing our developer docs to catalogue our examples.
=> Tidying OMERO developer docs

omero/sysadmins/version-requirements.txt
Cherry-picked relevant commit from https://github.com/openmicroscopy/ome-documentation/pull/1231
=> omero: Correct ZeroC forum URLs (all invalidated)

omero/developers/GettingStarted.txt
Adds useful links for those new to HQL. Staged at http://www.openmicroscopy.org/site/support/omero5.1-staging/developers/GettingStarted.html#examples.
--rebased-from #1250
=> Link query references (rebased from develop)
